
<div id="admin-page-body" class="row">
    <div class="col-sm-3">
        <h4 id="reports-header">REPORTS</h4>
        <div id="reports-nav" class="list-group">
            <button type="button" id="report1-nav-item" class="active list-group-item reports-nav-items">Monthly sick-leave (overall)</button>
            <button type="button" id="report2-nav-item" class="list-group-item reports-nav-items">Monthly sick-leave by Department</button>
            <button type="button" id="report3-nav-item" class="list-group-item reports-nav-items">Monthly sick-leave by Individual</button>
            <button type="button" id="report4-nav-item" class="list-group-item reports-nav-items">Yearly sick-leave (overall)</button>
            <button type="button" id="report5-nav-item" class="list-group-item reports-nav-items">Yearly sick-leave by Department</button>
            <button type="button" id="report6-nav-item" class="list-group-item reports-nav-items">Yearly sick-leave by Individual</button>
        </div>
    </div>
    <div class="col-sm-9">
        <h2>Report Title</h2>
        <div id="chart-container"></div>
    </div>
</div>

<script src="<?= BASE_URL ?>/assets/3rd/js/reports.js" type="text/javascript"></script>

<script type="text/javascript">
    $('#report1-nav-item').click();
    $(".reports-nav-items").click(function(){
        $(this).addClass("active").siblings().removeClass("active");
    });
</script>
