<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h2>Sick-leave filed for <span id="for_name"></span></h2>
            Created by <span id="author_name"></span>
        </div>
        <div class="col-sm-6 section-read">
            <h3>Read by <span id="read_by"></span></h3>
            
        </div>
    </div>
    <br>
    <br>
    <hr>
    <b>Sick-leave information</b>
</div>
