<!DOCTYPE html>
<html lang="en">

    <!-- Mirrored from getbootstrap.com/examples/starter-template/ by HTTrack Website Copier/3.x [XR&CO'2013], Mon, 06 Oct 2014 00:10:30 GMT -->
    <!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>YouSick</title>

        <link href="<?= BASE_URL ?>assets/3rd/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" href="http://css-spinners.com/css/spinner/whirly.css" type="text/css">
        <link href="<?= BASE_URL ?>assets/css/styles.css" rel="stylesheet">

        <script src="<?= BASE_URL ?>assets/3rd/jquery/jquery.min.js" type="text/javascript"></script>
        <script src="<?= BASE_URL ?>assets/3rd/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="<?= BASE_URL ?>bower_components/highcharts/highcharts.js" type="text/javascript" ></script>

        <script type="text/javascript">
            $.ajax({
                dataType: 'json',
                url: '<?= BASE_URL ?>/rest/get_session',
                success: function (session) {
                    if (!session.success)
                        location.href = '/home';
                    else {
                        if (!session.data.user.is_admin)
                            location.href = "/user";
                    }
                },
                async: false
            });
        </script>
    </head>

    <body>

        <div class="container-fluid">
            <div class="row header">
                <div class="col-xs-3">
                    <a href="/admin"><h1 class="logo col-xs-3">YouSick</h1></a>
                </div>
                <span class="col-xs-9">
                    <div class="btn-group pull-right">
                        <button  type="button" id="user-btn" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Loading</button>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="<?= BASE_URL ?>admin/new-sickleave" id="file-sl">File Sick Leave</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="<?= BASE_URL ?>admin/import-csv">Import Employee Details (CSV)</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#" id="logout">Logout</a></li>
                        </ul>
                    </div>
                </span>
            </div>

            <?= $_VIEW ?>


        </div><!-- /.container -->

        <script src="<?= BASE_URL ?>assets/3rd/js/user.js" type="text/javascript"></script>
        <script type="text/javascript">
            // Bind Logout
            $('#logout').click(function(e) {
                e.preventDefault();

                $.ajax({
                    url: '<?= BASE_URL ?>rest/logout_session',
                    contentType: 'json',
                    method: 'POST',
                    success: function(response) {
                        if (response.success)
                        {
                            window.location = '<?= BASE_URL ?>';
                        }
                    }
                });
            });

        </script>

</html>
