<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from getbootstrap.com/examples/starter-template/ by HTTrack Website Copier/3.x [XR&CO'2013], Mon, 06 Oct 2014 00:10:30 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>YouSick</title>

    <!-- jQuery -->
    <script src="assets/3rd/jquery/jquery.min.js" type="text/javascript"></script>

    <!-- Bootstrap core -->
    <link href="assets/3rd/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="assets/3rd/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
  </head>

  <body>

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">YouSick</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="?home">Home</a></li>
            <li><a href="?aboutus">About</a></li>
            <li><a href="?contactus">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
        <br>
        <br>
        <br>
        <?php echo $_VIEW; ?>

    </div><!-- /.container -->


</html>
