<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from getbootstrap.com/examples/starter-template/ by HTTrack Website Copier/3.x [XR&CO'2013], Mon, 06 Oct 2014 00:10:30 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>YouSick</title>

    <link href="assets/3rd/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />
	<link rel="stylesheet" href="http://css-spinners.com/css/spinner/whirly.css" type="text/css">
    <link href="assets/css/styles.css" rel="stylesheet">

    <script src="assets/3rd/jquery/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/bower_components/moment/min/moment.min.js"></script>
    <script src="assets/3rd/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
</head>

<body>

    <div class="container">
        <?php echo $_VIEW; ?>

    </div><!-- /.container -->


</html>
