<div class="row header">
    <div class="col-xs-6">
        <a href="/admin"><h1 class="logo col-xs-6">YouSick</h1></a>
    </div>
    <span class="col-xs-6">
        <div class="btn-group pull-right">
            <button  type="button" id="user-btn" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Loading</button>
            <ul class="dropdown-menu pull-right">
                <li><a href="/admin-add" id="file-sl">File Sick Leave</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Import Employee Details (CSV)</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="" id="logout">Logout</a></li>
            </ul>
        </div>
    </span>
</div>
<div id="admin-page-body" class="row">
    <div class="col-sm-3">
        <h4 id="reports-header">REPORTS</h4>
        <div id="reports-nav" class="list-group">
          <button type="button" id="report1-nav-item" class="active list-group-item reports-nav-items">Overall Sick Leave (Monthly)</button>
          <button type="button" id="report2-nav-item" class="list-group-item reports-nav-items">Overall Sick Leave (Yearly)</button>
          <button type="button" id="report3-nav-item" class="list-group-item reports-nav-items">All Departments Monthly Sick Leave</button>
          <button type="button" id="report4-nav-item" class="list-group-item reports-nav-items">Single Department Monthly Sick Leave</button>
        </div>
    </div>
    <div class="col-sm-9">
        <h2>Report Title</h2>
        <div id="chart-container"></div>
    </div>
</div>

<script src="assets/3rd/js/user.js" type="text/javascript"></script>
<script src="assets/3rd/js/reports.js" type="text/javascript"></script>

<script type="text/javascript">
    $('#report1-nav-item').click();
    $(".reports-nav-items").click(function(){
        $(this).addClass("active").siblings().removeClass("active");
    });
</script>
