<div class="row header">
    <div class="col-xs-6">
        <a href="/admin"><h1 class="logo col-xs-6">YouSick</h1></a>
    </div>
    <span class="col-xs-6">
        <div class="btn-group pull-right">
            <button  type="button" id="admin-user-btn" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                aduser <span class="caret"></span>
            </button>
            <ul class="dropdown-menu pull-right">
                <li><a href="#">File Sick Leave</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Import Employee Details (CSV)</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Logout</a></li>
            </ul>
        </div>
    </span>
</div>
<div id="page-body" class="col-md-4 col-sm-6 col-xs-9 col-centered">
    <div id="user-header" class="row">
        <div id="name-wrapper">
            <h2>File Sick Leave</h2>
        </div>
    </div>
    <div class="vertical-space"></div>
    <form class="row form-horizontal" name="sickleave-form" method="post">
        <div class="form-group">
            <label for="employee-name-field" class="control-label col-md-3">Who</label>
            <div class="col-md-9 control-group">
                <select id="employee-name-field" class="form-control" placeholder="Select employee">
                    <option value="">Select a person...</option>
                </select>
            </div>
            <div class="col-md-3"></div>
            <div class="col-md-9">
                <label><strong>0/15</strong> Sick Leave Filed</label>
                <span class="pull-right">
                    <a href="">See history</a>
                </span>
            </div>
        </div>
        <div class="form-group">
            <label for="datetimepicker" class="control-label col-md-3">Date</label>
            <div class="col-md-9">
                <div class="input-group date" id="datetimepicker">
                    <input type="text" class="form-control"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="col-md-3"></div>
            <div class="col-md-9">
                <div class="col-md-6">
                    <label class="radio-inline">
                        <input type="radio" name="optionsRadios" id="whole-day-radion-btn" value="1" checked>
                        Whole day
                    </label>
                </div>
                <div class="col-md-6">
                    <label class="radio-inline">
                        <input type="radio" name="optionsRadios" id="half-day-radion-btn" value="0.5">
                        Half day
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="reason-field" class="control-label col-md-3">Reason</label>
            <div class="col-md-9">
                <input type="text" id="reason-field" class="form-control" name="reason"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3"></div>
            <div class="col-md-9">
                <input type="submit" id="file-sl-btn" class="btn btn-danger" value="File Sick Leave"/>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker').datetimepicker({
            format: 'LL',
            defaultDate: new Date()
            //extraFormats: ['YYYY-MM-DD']
        });

        var selectize = $('#employee-name-field').selectize({
            create: true,
            sortField: {
                field: 'text',
                direction: 'asc'
            },
            onItemAdd: function(value, $item) {
                console.log(value);
            }
        });

        var selectizeControl = selectize[0].selectize;

        $.ajax({
            dataType: 'json',
            url: '/rest/view_employees',
            success: function(employees) {
                if (employees.success)
                {
                    $.each(employees.data.collection, function(index, employee) {
                        selectizeControl.addOption({
                            value: employee.ID,
                            text: employee.name
                        });
                    });
                }
            }
        });

        $('#file-sl-btn').click(function() {
            var admin_id = 0;
            //var date = moment($('#datetimepicker').val(), "YYYY-MM-DD");
            //$('#datetimepicker').val(date);
            //console.log($('#datetimepicker').val());
            var data = $('#sl-form').serializeArray();
            //var data.date = moment(data.date, "YYYY-MM-DD");
            data.push({ author_id : admin_id });
            alert(data);
        });

        $('.logo').click(function() {
            window.location.href = '/admin';
        });
    });
</script>
