<div class="row header">
    <div class="col-xs-6">
        <h1 class="logo col-xs-6">YouSick</h1>
    </div>
    <span class="col-xs-6">
        <button id="admin-user-btn" class="btn btn-default btn-sm span-right" type="button">ausername</button>
    </span>
</div>
<div class="row">
    <div class="col-md-3 no-gutter">
        <div id="reports-nav" class="list-group">
          <button type="button" class="list-group-item">Cras justo odio</button>
          <button type="button" class="list-group-item">Dapibus ac facilisis in</button>
          <button type="button" class="list-group-item">Morbi leo risus</button>
          <button type="button" class="list-group-item">Porta ac consectetur ac</button>
          <button type="button" class="list-group-item">Vestibulum at eros</button>
        </div>
    </div>
    <div id="report-container" class="col-md-9">
        <h1>Sample</h1>
    </div>
</div>
