<div class="jumbotron">
    <h1>YouSick</h1>
    <h4>A simple and lightweight sick-leave notification system</h4>
</div>
<div class="col-md-4 col-centered">
    <div id="user-header" class="row">
        <div id="name-wrapper">
            <h2>Name</h2>
        </div>
        <!--
        <div id="sl-count-wrapper" class="col-md-3">
            <div class="row">
                <label>SL</label>
                <a href="">15/15</a>
            </div>
        </div>
        -->
    </div>
    <div class="vertical-space"></div>
    <form class="row form-horizontal" name="sickleave-form" method="post">
        <div class="form-group">
            <label for="datetimepicker" class="control-label col-md-3">Date</label>
            <div class="form-group col-md-9">
                <div class='input-group date' id='datetimepicker'>
                    <input type='text' class="form-control"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="col-md-3"></div>
            <div class="col-md-9">
                <div class="col-md-6">
                    <label class="radio-inline">
                        <input type="radio" name="optionsRadios" id="whole-day-radion-btn" value="1" checked>
                        Whole day
                    </label>
                </div>
                <div class="col-md-6">
                    <label class="radio-inline">
                        <input type="radio" name="optionsRadios" id="half-day-radion-btn" value="0.5">
                        Half day
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="reason-field" class="control-label col-md-3">Reason</label>
            <div class="col-md-9">
                <input type="text" id="reason-field" class="form-control" name="reason"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3"></div>
            <div class="col-md-9">
                <input type="submit" class="btn btn-danger" value="File Sick Leave"/>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker').datetimepicker();
    });
</script>
