<div class="row-fluid">
    <div align="center">
        <h2>Enter your Password to start</h2>
        <br>
        <div class="col-lg-4" style="float:none">
            <form name="UsernameForm" method="post">
                <span class="input-group">
                    <input type="text" class="form-control textbox-large" name="username" maxlength="15">
                    <span class="input-group-btn">
                        <input type="submit" id="START" class="btn btn-danger large" value="Start">
                    </span>
					<div id="spinner" class="whirly-loader">
						Loading…
					</div>
                </span>
            </form>
        </div>
    </div>
</div>