<div class="jumbotron">
    <h1>PeopleSearch</h1>
    <h4>Where people becomes searchable</h4>
</div>
<div class="row">
    <div class="col-sm-4 col-md-4 col-lg-4">
        <div class="jumbotron">
            <h3>Heading</h3>
            Body here
        </div>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <div class="jumbotron">
            <h3>Heading</h3>
            Body here
        </div>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <div class="jumbotron">
            <h3>Heading</h3>
            Body here
        </div>
    </div>
</div>