<div class="row header">
    <div class="col-xs-6">
        <a href="/admin"><h1 class="logo col-xs-6">YouSick</h1></a>
    </div>
    <span class="col-xs-6">
        <div class="btn-group pull-right">
            <button  type="button" id="user-btn" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </button>
            <ul class="dropdown-menu pull-right">
                <li><a href="/user">File Sick Leave</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="" id="logout">Logout</a></li>
            </ul>
        </div>
    </span>
</div>
<div class="col-md-4 col-sm-6 col-xs-9 col-centered">
    <div id="user-header" class="row">
        <div id="name-wrapper">
            <h2 id="name">Loading...</h2>
            <label><strong>0/15</strong> Sick Leave Filed</label>
            <span class="pull-right">
                <a href="<?= BASE_URL ?>user/history">See history</a>
            </span>
        </div>
    </div>
    <div class="vertical-space"></div>
    <form id="fileSickLeave" class="row form-horizontal" name="sickleave-form" method="post">
        <div class="form-group">
            <label for="datetimepicker" class="control-label col-md-3">Date</label>
            <div class="col-md-9">
                <div class="input-group date" id="datetimepicker">
                    <input name="date" id="date" type="text" class="form-control"/>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="col-md-3"></div>
            <div class="col-md-9">
                <div class="col-md-6">
                    <label class="radio-inline">
                        <input type="radio" name="span" id="spanWhole" value="1" checked>
                        Whole day
                    </label>
                </div>
                <div class="col-md-6">
                    <label class="radio-inline">
                        <input type="radio" name="span" id="spanHalf" value="0.5">
                        Half day
                    </label>
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="reason-field" class="control-label col-md-3">Reason</label>
            <div class="col-md-9">
                <input type="text" id="reason" class="form-control" name="reason"/>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-3"></div>
            <div class="col-md-9">
                <input type="submit" class="btn btn-danger" value="File Sick Leave"/>
            </div>
        </div>
    </form>
</div>

<script src="assets/3rd/js/user.js" type="text/javascript"></script>

<script type="text/javascript">
    $.ajax({
        dataType: 'json',
        url: '<?= BASE_URL ?>/rest/get_session',
        success: function (session) {
            if (session.success)
            {
                $('#name').html(session.data.user.name + "  <span class='caret'></span>");
                $('#user-btn').html(session.data.user.username + "  <span class='caret'></span>")
            }
        }
    });

    $('#datetimepicker').datetimepicker({
        format: 'LL',
        defaultDate: new Date()
    });

    $("#fileSickLeave").submit(function (e) {
        e.preventDefault();


        var jsDate = new Date($('#date').val());
        var date = moment(jsDate).format('YYYY-MM-DD');
        $('#date').val(date);

        var data = $('#fileSickLeave').serialize() + "&author_id=" + user_id + "&for_id=" + user_id;
        console.log(data);

        $.ajax({
            method: 'POST',
            url: '/rest/create_sickleave',
            data: data,
            success: function (retData) {
                if (retData.success)
                {
                    alert("Success: " + retData.message);

                    if (retData.data.has_state && !retData.data.state.success)
                        alert(retData.data.state.message);

                    window.location.replace('<?= BASE_URL ?>user/history')
                } else {
                    if (retData.has_state && !retData.data.state.success)
                        alert("Failed: " + retData.data.state.message);
                    else
                        alert("Failed: " + retData.message);
                }
            }
        });
    });
    // Bind Logout
    $('#logout').click(function (e) {
        e.preventDefault();

        $.ajax({
            url: '<?= BASE_URL ?>rest/logout_session',
            contentType: 'json',
            method: 'POST',
            success: function (response) {
                if (response.success)
                {
                    window.location = '<?= BASE_URL ?>';
                }
            }
        });
    });
</script>

